### ISSUE TITLE
When "Tailwind" framework is selected on the demo site - the JS file goes missing.

### ISSUE THREAD

**Issue by ColoradoWebGuy** [CodyHouse/cd-looping-tabs-changelog#1]
When the "Tailwind" framework is selected for the "Looping Tabs" component. The javascript goes missing. 

[https://codyhouse.co/ds/components/app/looping-tabs](https://codyhouse.co/ds/components/app/looping-tabsl)

As a workaround, I copied the JS from the "CodyFrame" framework option.

![JSMissing-LoopingTabs](https://user-images.githubusercontent.com/6867492/185133929-0d25334f-af64-4127-8940-6a3b06bbfc3c.jpg)

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up. This has been fixed now. Cheers!

**Comment by ColoradoWebGuy** [comment]
Awesome. Glad to help. Cheers!
